buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://repo.grails.org/grails/core" }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        
        // REQUIRED: This plugin handles the 'runtime' configurations correctly for Spring Boot
        classpath "org.springframework.boot:spring-boot-gradle-plugin:2.7.18"
        
        classpath "org.grails:grails-gradle-plugin:$grailsGradlePluginVersion" // there is no version 5.3.6

        // UPDATE: Asset-pipeline 3.x+ is required for Groovy 3 / Grails 5 compatibility
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.4.7"
    }
}

version "0.1.2"
group "grails.security.stateless.ng"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.springframework.boot"
apply plugin:"org.grails.grails-plugin"
// apply plugin:"org.grails.grails-plugin-publish"
apply plugin:"org.grails.grails-gsp"
apply plugin: "com.bertramlabs.asset-pipeline"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-rest"
    //implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-plugin-interceptors"
    //implementation "org.grails.plugins:cache"
    implementation "org.grails.plugins:async"
    implementation "org.grails.plugins:scaffolding"
    implementation "org.grails.plugins:gsp"
    console "org.grails:grails-console"
    profile "org.grails.profiles:web-plugin"
    compileOnly "org.grails:grails-plugin-services"
    //provided "org.grails:grails-plugin-domain-class"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:2.14.2"
    testImplementation "org.grails:grails-gorm-testing-support"
    testImplementation "org.grails:grails-plugin-testing"
    //testImplementation "org.grails.plugins:geb"
    testImplementation "org.grails:grails-web-testing-support"
    //testImplementation "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
    //testImplementation "net.sourceforge.htmlunit:htmlunit:2.18"

    implementation group: 'joda-time', name: 'joda-time', version: '2.10.1'
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}
// enable if you wish to package this plugin as a standalone application
bootJar.enabled = false

/*
grailsPublish {
    // TODO: Provide values here
    user = 'user'
    key = 'key'
    githubSlug = 'foo/bar'
    license {
        name = 'Apache-2.0'
    }
    title = "Stateless Security NG Grails Plugin"
    desc = "Full plugin description"
    developers = [ppazos:"Pablo Pazos"]
}
*/

assets {
    packagePlugin = true
}
